[package]
name = "near_hunter_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "5.1.0"
serde = {"1.0.202", features= ["derive"] }
serde_json = "1.0"
